### PR TITLE
Added the ability to add more tests with "Test" suffix on the class

### PR DESCRIPTION
**Pull request by Drawaes**
Also added nuget.config file with path to benchmarkdotnet's overnight repo in case it's needed

I will now add some actual tests if you are keen, I just didn't want to do that change and this in the same set to confuse the issue

### CODE REVIEW

**Comment by NickCraver** [comment]
I'd opt for stable over nightly (it's version locked anyway), are the other bits .NET Core compatible for when we add multiple framework builds? (so you could benchmark each)

**Comment by Drawaes** [comment]
Sure I agree, I wouldn't change it now, but having the nuget file in there makes it easy to flick around if there is a new feature, or bugfix you want to try out. Happy to remove it either way as you say the actual version used is version locked.

Made a small change to make it .net Core compatible (will need the System.Reflection package when its done though but that will be fine). 

Added a batchfile that builds it in release and then runs it from it's directory, cause it's annoying to forget to build it in release and run it from the cmd not getting the latest changes (many hours wondering why changes had no effect).

**Comment by Drawaes** [comment]
Sorry, I put the dictionary vs array test in here, anyway results are below which shows for small lists don't use dictionaries but be careful because it blows out quickly. The reverse test should nuke the read ahead on the cpu, but could be better and be a pseudo random guess for each step of the loop.

|         Method | ItemsInList |        Mean |    StdErr |    StdDev |      Median | Scaled |
|--------------- |------------ |------------ |---------- |---------- |------------ |------- |
|     Dictionary |           5 |  19.7912 ns | 0.0057 ns | 0.0206 ns |  19.7842 ns |   1.00 |
|          Array |           5 |   6.8459 ns | 0.0205 ns | 0.0794 ns |   6.8115 ns |   0.35 |
| ArrayBackwards |           5 |   6.3646 ns | 0.0132 ns | 0.0512 ns |   6.3412 ns |   0.32 |
|     Dictionary |          10 |  19.1937 ns | 0.0579 ns | 0.2165 ns |  19.0867 ns |   1.00 |
|          Array |          10 |  12.1171 ns | 0.1558 ns | 1.5579 ns |  11.4469 ns |   0.63 |
| ArrayBackwards |          10 |   9.9032 ns | 0.0080 ns | 0.0298 ns |   9.9040 ns |   0.52 |
|     Dictionary |          20 |  19.0729 ns | 0.0170 ns | 0.0612 ns |  19.0510 ns |   1.00 |
|          Array |          20 |  27.3048 ns | 0.0751 ns | 0.2910 ns |  27.3708 ns |   1.43 |
| ArrayBackwards |          20 |  20.7323 ns | 0.0190 ns | 0.0736 ns |  20.7345 ns |   1.09 |
|     Dictionary |          50 |  19.0702 ns | 0.0082 ns | 0.0306 ns |  19.0688 ns |   1.00 |
|          Array |          50 |  49.7238 ns | 0.1185 ns | 0.4433 ns |  49.7120 ns |   2.61 |
| ArrayBackwards |          50 |  52.9418 ns | 0.2003 ns | 0.7759 ns |  52.8394 ns |   2.78 |
|     Dictionary |         100 |  19.0589 ns | 0.0120 ns | 0.0450 ns |  19.0507 ns |   1.00 |
|          Array |         100 |  86.2183 ns | 0.3209 ns | 1.1571 ns |  86.1704 ns |   4.52 |
| ArrayBackwards |         100 | 100.4909 ns | 0.2678 ns | 1.0019 ns | 100.7518 ns |   5.27 |

**Comment by NickCraver** [comment]
Can we pull the `nuget.config` out so we're pointing at a stable release for people to test on? Looking to merge in ASAP after that.

**Comment by Drawaes** [comment]
Done

**Comment by NickCraver** [comment]
Merged!

**Comment by Drawaes** [comment]
Yay, now we can make this a thing, then when people say "nah that's not true" I can point them to this repo and say, try it out for yourself! I have some crazy ideas for what could be done.. might try to bake them more before giving them airtime

**Pull request merged**
